export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const GET_VGAME_BY_ID = 'GET_VGAME_BY_ID';
export const GET_VGAMES_BY_NAME = 'GET_VGAMES_BY_NAME';
export const GET_GENERO = 'GET_GENERO';
export const POST_VGAME = 'POST_VGAME';
export const  GENRES_FILTER= ' GENRES_FILTER';
export const ORIGEN_FILTER= 'ORIGEN_FILTER'